version: '3.4'

services:
  on-event:
    image: lambci/lambda:nodejs12.x
    volumes:
      - ./dist/resources/on-event:/var/task:ro,delegated
    ports:
      - ${ELASTICSEARCH_INDEX_ON_EVENT_PORT:-9001}:9001
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DOCKER_LAMBDA_STAY_OPEN: 1
      DOCKER_LAMBDA_WATCH: 1
      ELASTICSEARCH_ENDPOINT: http://elasticsearch:9200
      ELASTICSEARCH_INDEX: test-index
      S3_BUCKET_NAME: test-bucket
      S3_OBJECT_KEY: test-object-key
      S3_ENDPOINT: http://mockserver:1080
      CONTEXT_MISSING_STRATEGY: LOG_ERROR
    command: handler.handler
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    ports:
      - ${ELASTICSEARCH_INDEX_ES_PORT:-9200}:9200
    environment:
      discovery.type: single-node

  mockserver:
    image: mockserver/mockserver:mockserver-5.9.0
    ports:
      - ${ELASTICSEARCH_INDEX_MOCKSERVER_PORT:-1080}:1080
